# Generated by Django 3.0 on 2021-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdetails',
            name='no_of_childrens',
            field=models.IntegerField(null=True),
        ),
    ]
